name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    - name: Configure gcloud
      run: |
        echo "Configuring gcloud..."
        gcloud config set project YOUR_PROJECT_ID
        gcloud config set run/region YOUR_CLOUD_RUN_REGION

    - name: Build and push container
      run: |
        echo "Building and pushing container..."
        gcloud builds submit --tag gcr.io/YOUR_PROJECT_ID/YOUR_SERVICE_NAME

    - name: Deploy to Cloud Run
      run: |
        echo "Deploying to Cloud Run..."
        gcloud run deploy YOUR_SERVICE_NAME \
          --image gcr.io/YOUR_PROJECT_ID/YOUR_SERVICE_NAME \
          --platform managed \
          --region YOUR_CLOUD_RUN_REGION \
          --allow-unauthenticated
