name: Build and Deploy to App Engine

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        version: 'latest'

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    - name: Configure gcloud
      run: |
        echo "Configuring gcloud..."
        gcloud config set project imponet-7ba0a
        gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Build and push Docker image
      run: |
        echo "Building Docker image..."
        docker build -t us-central1-docker.pkg.dev/imponet-7ba0a/serverpod-production-container/imposerver:latest ./imposerver_server
        echo "Pushing Docker image..."
        docker push us-central1-docker.pkg.dev/imponet-7ba0a/serverpod-production-container/imposerver:latest

    - name: Deploy to App Engine
      run: |
        echo "Deploying to App Engine..."
        gcloud app deploy ./imposerver_server/app.yaml --image-url=us-central1-docker.pkg.dev/imponet-7ba0a/serverpod-production-container/imposerver:latest --quiet
